version: "2"
services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
    - "3002:3002"
    - "9230:9230"
    volumes:
      - .:/app
    depends_on:
    - mongo
    networks:
    - app_network
  mongo:
    image: mongo
    ports:
    - "27017:27017"
    networks:
      - app_network
networks:
  app_network:
    driver: bridge
