version: "2"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-prod
    ports:
    - "3001:3001"
    - "9229:9229"
    volumes:
      - .:/app
    depends_on:
    - mongo
  mongo:
    image: mongo
    ports:
    - "27017:27017"
